"""Add company logo_url

Revision ID: 8687308f8457
Revises: 001
Create Date: 2026-05-29 22:54:54.226185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8687308f8457'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('integration_configs', sa.Column('sair_company_id', sa.String(length=100), nullable=True))
    op.add_column('integration_configs', sa.Column('sair_api_key', sa.String(length=255), nullable=True))
    op.drop_column('integration_configs', 'sayr_api_key')
    op.drop_column('integration_configs', 'sayr_company_id')
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_column('users', 'telegram_chat_id')
    op.add_column('integration_configs', sa.Column('sayr_company_id', sa.VARCHAR(length=100), nullable=True))
    op.add_column('integration_configs', sa.Column('sayr_api_key', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('integration_configs', 'sair_api_key')
    op.drop_column('integration_configs', 'sair_company_id')
    op.drop_column('companies', 'logo_url')
    # ### end Alembic commands ###
